version: '3'

services:
  db:
    image: postgres
  web:
    image: matiaslionel/pruebadjango
    command: python /projecto/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./volumen:/code
    ports:
      - "8000:8000"
    depends_on:
      - db